// User Roles
const ROLES = {
  GUEST: 'GUEST',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
};

// Loyalty Card Statuses
const LOYALTY_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
};

// Stamp Statuses
const STAMP_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

// Redemption Statuses
const REDEMPTION_STATUS = {
  AVAILABLE: 'AVAILABLE',
  REDEEMED: 'REDEEMED',
  EXPIRED: 'EXPIRED',
};

// Reward Types
const REWARD_TYPES = {
  COMPLIMENTARY_ITEM: 'COMPLIMENTARY_ITEM',
  DISCOUNT_PERCENTAGE: 'DISCOUNT_PERCENTAGE',
  DISCOUNT_FLAT: 'DISCOUNT_FLAT',
  FREE_BEVERAGE: 'FREE_BEVERAGE',
  SPECIAL_EXPERIENCE: 'SPECIAL_EXPERIENCE',
  CUSTOM: 'CUSTOM',
};

// Audit Actions
const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GUEST_REGISTERED: 'GUEST_REGISTERED',
  STAMP_REQUESTED: 'STAMP_REQUESTED',
  STAMP_APPROVED: 'STAMP_APPROVED',
  STAMP_REJECTED: 'STAMP_REJECTED',
  REWARD_CREATED: 'REWARD_CREATED',
  REWARD_UPDATED: 'REWARD_UPDATED',
  REWARD_REDEEMED: 'REWARD_REDEEMED',
  REWARD_UNLOCKED: 'REWARD_UNLOCKED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  STAFF_CREATED: 'STAFF_CREATED',
  STAFF_UPDATED: 'STAFF_UPDATED',
  ROYAL_SURPRISE_PLAYED: 'ROYAL_SURPRISE_PLAYED',
  REVIEW_CLICKED: 'REVIEW_CLICKED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
};

// Audit Entity Types
const ENTITY_TYPES = {
  USER: 'User',
  LOYALTY_CARD: 'LoyaltyCard',
  STAMP: 'Stamp',
  REWARD: 'Reward',
  REDEMPTION: 'RewardRedemption',
  REVIEW: 'ReviewEvent',
  SETTINGS: 'RestaurantSettings',
};

// Error Codes
const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT: 'RATE_LIMIT',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

// Pagination defaults
const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

module.exports = {
  ROLES,
  LOYALTY_STATUS,
  STAMP_STATUS,
  REDEMPTION_STATUS,
  REWARD_TYPES,
  AUDIT_ACTIONS,
  ENTITY_TYPES,
  ERROR_CODES,
  PAGINATION,
};
